// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// i2s_rx_master //
// ------------- //

#define i2s_rx_master_wrap_target 0
#define i2s_rx_master_wrap 14
#define i2s_rx_master_pio_version 0

#define i2s_rx_master_offset_entry_point 0u

static const uint16_t i2s_rx_master_program_instructions[] = {
            //     .wrap_target
    0xa842, //  0: nop                    side 1
    0xa842, //  1: nop                    side 1
    0xa042, //  2: nop                    side 0
    0xe037, //  3: set    x, 23           side 0
    0xa842, //  4: nop                    side 1
    0x4801, //  5: in     pins, 1         side 1
    0x0044, //  6: jmp    x--, 4          side 0
    0xe026, //  7: set    x, 6            side 0
    0xa842, //  8: nop                    side 1
    0xa842, //  9: nop                    side 1
    0x0048, // 10: jmp    x--, 8          side 0
    0xf03f, // 11: set    x, 31           side 2
    0xb842, // 12: nop                    side 3
    0xb842, // 13: nop                    side 3
    0x104c, // 14: jmp    x--, 12         side 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_rx_master_program = {
    .instructions = i2s_rx_master_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = i2s_rx_master_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_rx_master_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_rx_master_wrap_target, offset + i2s_rx_master_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

