//////OK LET ME MAKE MYSELF CLEAR. I AM DOING A MICROPROCESSOR EMBEDDED SYSTEM PROJECT WHERE I WILL HAVE 6 PERIPHERALS. ONE MIC SPEAKING TO AN SD CARD IN PIO TO IMPLEMENT I2S. ONE KEYBOARD TALKING TO THE MICROCONTROLLER IN GPIO. ONE POT TALKING TO THE MICROCONTROLLER FOR ADC (VOLUME KNOB). A TFT DISPLAY (SPI). THE SD CARD TLAKING TO THE MICROCONTROLLER GIVING AUDIO FILES RECORD FROM THE MICROCONTROLLER ALSO IN SPI. DO YOU UNDERSTAND? THE MICROCONTROLLER WE ARE USING IS AN RP2350. WHEN YOU CLICK THE BUTTON 0, YOU ARE IN THE PLAYING STATE. IF YOU CLICK THE BUTTON ASTERISK YOU ARE IN THE RECORDING STATE. THE AUDIO'S WILL BE ONE SECOND LONG. BASICALLY ONCE YOU CLICK ASTERISK, YOU CAN CLICK ANY OTHER BUTTON ON THE KEYPAD OTHER THAN 0 AND RECORED A SOUND FOR IT WITHIN ONE SECOND. I WANT THE TFT DISPLAY TO DISPLAY THE VOLUME AND THE RECORDING STATE (MAYBE A SMALL COOL LITTLE TIMER TO SAY HOW MUCH YOU HAVE LEFT IN RECORDING THAT DECAYS, 1 SECOND). HERE ARE THE PINS BEING USED: Component Pins Peripheral PWM Audio Out GP0 Vcc Gnd PWM0 A Keypad (4x4) GP2, 3, 4, 5 (Rows) / GP6, 7, 8, 9 (Cols) SIO (GPIO) TFT Display GP10 (SCK), 11 (TX), 12 (RX), 13 (CSn) SPI1 TFT Control GP14 (DC), 15 (RST) Vcc Gnd SIO (GPIO) SD Card GP16 (RX), 17 (CSn), 18 (SCK), 19 (TX) Vcc Gnd SPI0 Microphone GP20 (CLK), 21 (WS), 22 (DATA) Vcc Gnd PIO0 Volume ADC GP45 Vcc Gnd for Pot ADC3 CAN WE START WORKING TOGETHER? DONT MAKE ANY SOURCE FILES YET, JUST START THINKING ABOUT THE GEENRAL MAIN.C FILE AND SUCH WHILE I SET UP TFT AND THEN WHEN I NEED YOUR HELP WE CAN TALK. REPEAT TO ME WHAT YOU UNDERSTOOD

#ifndef QUEUE_H
#define QUEUE_H

#include <hardware/timer.h>
#include "pico/stdlib.h"

typedef struct {
    uint16_t q[32];
    uint16_t head;
    uint16_t tail;
} KeyEvents;

extern KeyEvents kev; 

static inline uint16_t key_pop() {
    while (kev.head == kev.tail) {
        sleep_ms(10);   
    }
    uint16_t value = kev.q[kev.tail];
    kev.tail = (kev.tail + 1) % 32;
    return value;
}

static inline void key_push(uint16_t value) {
    if ((kev.head + 1) % 32 == kev.tail) {
        return; 
    }
    kev.q[kev.head] = value;
    kev.head = (kev.head + 1) % 32;
}

#endif